Allow configurable HTTP Client library
ueberauth/oauth2 pull request #160
Opened 2021-11-11 21:42 UTC by alexgleason

Users can supply their own HTTP Client module to be used by OAuth2.Request:

```elixir
config :oauth2, http_client: MyCustomClient
```

The default is `OAuth2.HTTPClient.Hackney` which conforms to the `OAuth2.HTTPClient` behaviour.

I am writing a Ueberauth strategy using this library, and I want to be able to mock the HTTP client for automated tests. Making it configurable allows that to be possible. There are other legitimate reasons someone might want to provide their own module.

2021-11-12 13:12 UTC, scrogson submitted a review, later dismissed
❤️

2021-11-12 13:31 UTC, scrogson requested changes
Thank you for creating this PR, much appreciated.

I'm very much in favor of this PR, but I think we need to tweak it slightly. I'm not sure the `body/2` callback would work for all clients?

I think it would be nice to model after this package: https://github.com/peburrows/goth/blob/master/lib/goth/http_client.ex

Here is an example of a [Finch](https://github.com/sneako/finch) client implementation: https://github.com/wojtekmach/goth/blob/master/lib/goth/http_client/finch.ex

I think this will require a bit more tweaking to pull off, but I think this is the way to go. What do you think?

2022-01-04 07:05 UTC, yordis commented
Would be prudent to leverage https://github.com/teamon/tesla?

2022-01-20 10:21 UTC, gmile approved these changes

2022-01-20 17:59 UTC, yordis requested changes

2022-01-20 17:59 UTC, yordis commented on lib/oauth2/request.ex
> +  @http_client Application.get_env(:oauth2, :http_client, OAuth2.HTTPClient.Hackney)
Almost missed this one,

If we do it this way, people may need to know that they need to recompile things if a dependency changes. 

By now, I would suggest to remove it from module attributes into a function

```elixir
defp http_client
  Application.get_env(:oauth2, :http_client, OAuth2.HTTPClient.Hackney)
end
```

2022-04-26 19:31 UTC, escobera commented
> Would be prudent to leverage https://github.com/teamon/tesla?

I'm +1 for this, this abstracts away different http client internals so there's no need to create multiple adapters.

2023-01-29 22:02 UTC, closed without merging

2023-01-29 22:03 UTC, yordis commented
This is possible in the latest version using `Tesla`.

@alexgleason thank you so much for the work regardless.

2023-01-29 22:13 UTC, alexgleason commented
Cool!